name:                task
version:             0.1.0.0
license:             Unlicense

default-extensions:
  - DerivingStrategies

dependencies:
  - base

library:
  source-dirs:      src

tests:
  task-tests:
    source-dirs:      test
    main: Main.hs
    dependencies:
    - tasty
    - tasty-hspec
    - hspec
    - task
    - QuickCheck
